### PR TITLE
Fixed Background Aspect Ratio

### PR DESCRIPTION
**Pull request by gracebarsny**
**Prefabs**
- HomeUI: added aspect ratio fitters to Living Room and Yard backgrounds

### CODE REVIEW

**Comment by imann24** [comment]
@gracebarsny there is some gray space on the left:

image

**Comment by imann24** [comment]
@gracebarsny Let me know whether you plan to add more to this PR or whether it's ready to e merged

**Comment by gracebarsny** [comment]
I still need to fix it. Can you verify whether it's working on your computer?

**Comment by imann24** [comment]
Looks good to me! No more gray on the left side.

**Comment by gracebarsny** [comment]
Oh! And the height looks good?

**Comment by imann24** [comment]
Looks fine to me but maybe I'm missing something:
image

**Comment by gracebarsny** [comment]
Looks perfect! Go ahead and merge it if you feel comfortable.

**Pull request merged**
