### PR TITLE
Adding tunings and working on scouting logic

### PR DESCRIPTION
**Pull request by imann24**
**JSON**
- Adding tuning variables JSON

**Scripts**
- Added new event subscriptions to Dog.cs (delegates that can pass the dog and/or a float as an arg)
- Added Beginnings of scouting logic to PPGameController.cs
- Parsing the tunings vars into PPGameController.cs from the JSON file

### CODE REVIEW

**Comment by gracebarsny** [comment]
I'm going to merge this so I can get working on my own stuff. Make sure your spacing is consistent moving forward. Additionally, if you're going to insist on production-ready code, then you really should comment your work.

**Comment by imann24** [comment]
@gracebarsny What do you mean about consistent spacing? Bracket conventions?

After Winter Studio, I can fill in a TDD w/ agreed upon conventions. Personally I prefer K&R Style brackets (https://en.wikipedia.org/wiki/Indent_style). As for comments, I believe methods and var names should be self expressive. Therefore, I only think comments are necessary for specifics and justification that the code does not reveal.

Can we setup a video call with @Metkis to discuss and agree upon conventions?

**Comment by gracebarsny** [comment]
You don't always leave a space between methods or after class declarations. Yes, we should set up a call.

**Comment by imann24** [comment]
Oh gotcha, yeah, definitely worth defining a convention for that too. I never pay good attention to it. And for var casing. In future, I encourage you to comment those kind of things and request revisions before merging. I can quickly fix those.

Will move to Slack to discuss setting up a time

**Pull request merged**
