### PR TITLE
Removed Rehome Button & Fixed Dog Feeding Bug

### PR DESCRIPTION
**Pull request by gracebarsny**
**Prefabs**
- DogBrowser: removed rehome button gameobject

**Scripts**
- CurrencyData: made it so that canAfford() will always return false if amount is <= 0 (previously you could fill the dog bowl with 0 dog food as long as you didn't adopt any dogs yet).
- DogBrowserButtonController: removed rehome button variable and its refs

### CODE REVIEW

**Comment by imann24** [comment]
@gracebarsny still able to fill the dog bowl (even though it costs 0) 

image

**Comment by imann24** [comment]
image

**Comment by imann24** [comment]
Hold on, I think git didn't update correctly for some reason. Give me another sec

**Comment by gracebarsny** [comment]
@imann24 Yeah, it should have the new backgrounds.

**Comment by imann24** [comment]
I can still fill the dog bowl for free if I buy dog food but don't adopt dogs. Is this intentional?

image

**Comment by gracebarsny** [comment]
@imann24 That should be okay. But we should probably put something in place to prevent it from disappearing -- since no dogs will be there to eat it.

**Comment by imann24** [comment]
I was thinking just dodge that entirely: 

image

**Comment by gracebarsny** [comment]
@imann24 Even better!

**Comment by imann24** [comment]
Cool, I'll push that. Should be good to merge after that unless you want to look it over first

**Comment by gracebarsny** [comment]
Nope, it's all yours.

**Pull request merged**
