### PR TITLE
Fixed Timers Freezing When Game Paused

### PR DESCRIPTION
**Pull request by gracebarsny**
Fixed bug that daily gift and scouting timers would freeze whenever the game was paused so progress was lost.

**Prefabs**
- Game: set saveOnApplicationPause equal to true

### CODE REVIEW

**Comment by imann24** [comment]
@gracebarsny how are you verifying this fix? When I navigation to another window on my computer then jump back, the timer does not update. I think in addition to saving `OnApplicationPause` we also need to update the timers upon `OnApplicationPause(false)` being called.

**Comment by gracebarsny** [comment]
Hmm, it worked for me. Both the gift timer and scouting timers properly updated... I'll look into it.

**Comment by imann24** [comment]
@gracebarsny neither is working on my machine. Let me just make sure it's actually running the call to save

**Comment by imann24** [comment]
Yeah, the save call is definitely running. I feel like we're missing logic here to update the timers. I don't recall writing it previously.

**Comment by imann24** [comment]
Closing PR for now. Will re-open later w/ additional fixes.

**Pull request closed without merging**
