### PR TITLE
Implementing daily gift feature

### PR DESCRIPTION
**Pull request by imann24**
**Sprites**
- Added new gift icon
- Added new dialogue box icon

**File Structure**
- Shuffled some file structures around to be cleaner

**Prefabs**
- Overhauled the ScoutingReportUI prefab / script to be more general purpose for any gift received
- Added the daily gift logic to the CurrencyPanel prefab

**Scripts**
- Daily gift logic in `CurrencyPanel`
- Overhauled the delegate system for `CurrencySystem.cs`
- Added `ISubscribable` interface to begin to centralize delegate subscription logic
- Created `CurrencyFactory` for creating currency subclasses based on type / value (can basically convert info from JSON parallel arrays directly into C# data
- Improvements to timer logic (e.g. the timer actually stops when it hits zero)

### CODE REVIEW

**Comment by gracebarsny** [comment]
Several MCs in this branch now that I've merged the fix/spaces-in-directories PR.

**Comment by imann24** [comment]
@gracebarsny Those should be resolved

**Comment by imann24** [comment]
@gracebarsny #2 should be resolved. #1 seems like a relatively trivial bug that likely has a very complex fix (I would guess it's something to do w/ how Unity scene loading affects coroutines, but I'm not sure). Happy to discuss more at length if you feel it's necessary to address, but would advise adding to the Production Backlog for the time being

**Comment by gracebarsny** [comment]
@imann24 We'll absolutely add it to the backlog. We may find an easy fix along the way (such as a quick loading screen between scenes like they have in Klepto), or it may be something we only notice in the editor and not the builds.

**Pull request merged**
